#!/usr/bin/env bash
set -x
set -e

/usr/bin/qdbus --system org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.DeleteUser 1000 true
/usr/bin/pkcon -y remove calamares-plasmalnf netrunner-pinebook-calamares
/sbin/resize2fs /dev/mmcblk0p1
